### ISSUE TITLE
igvtools count function

### ISSUE THREAD

**Issue by radaniba** [broadinstitute/IGV#100]
Hello

I am trying to understand what the count function in igvtools in IGV is doing exactly but it is a little bit confusing from the doc on the website.

I am trying to look at non overlapping bins of 10MB and when I create the tdf from igv it is not really clear what is shown in the track, is it the average breadth of coverage (number of reads / bin size ) ? does it just count the number of reads regardless of the coverage (1X, 2X etc ..) how the Y axis is determined exactly ?

Thanks

**Comment by jrobinso** [comment]
Its the coverage averaged over the specified window size.
