### ISSUE TITLE
Setting feature window to 0 makes interval invisible

### ISSUE THREAD

**Issue by jpiper** [broadinstitute/IGV#113]
IGV version 2.3.40 - running on Mac OS X

It says in the help for the `set feature window` dialogue box to set to 0 to load everything, but in this case it leads to everything disappearing!

Steps to recreate.

put the following in test.bed

    track name="TEST TRACK PLEASE IGNORE"
    chr1	1	10000

use

    igvtools index test.bed

load test.bed into IGV and navigate to the region, e.g. `chr1:56-31,588`

set feature window to 0 on this track. The interval disappears!

**Comment by jrobinso** [comment]
Hi,

Yes, I discovered that myself.  It is fixed in the main trunk and will 
be released with 2.3.41.   Thanks for reporting it.

Jim

**Comment by jpiper** [comment]
Wonderful, thanks!
