### ISSUE TITLE
igv-2.3.40: package org.apache.tools.ant does not exist

### ISSUE THREAD

**Issue by mmokrejs** [broadinstitute/IGV#114]
I am trying to get https://github.com/broadinstitute/IGV/archive/v2.3.40.zip  compiled through Gentoo Linux package system but it fails here:

<pre>
>>> Configuring source in /mnt/1TB/var/tmp/portage/sci-biology/igv-2.3.40/work/IGV-2.3.40 ...
Rewriting attributes
Rewriting ./launcher/build.xml
Rewriting ./docs/publishedApiDoclet/build.xml
Rewriting ./build.xml
>>> Source configured.
>>> Compiling source in /mnt/1TB/var/tmp/portage/sci-biology/igv-2.3.40/work/IGV-2.3.40 ...
 * Using following ANT_TASKS: ant-apache-bcel
Buildfile: /mnt/1TB/var/tmp/portage/sci-biology/igv-2.3.40/work/IGV-2.3.40/build.xml

clean:

init:
    [mkdir] Created dir: /mnt/1TB/var/tmp/portage/sci-biology/igv-2.3.40/work/IGV-2.3.40/tmp
    [mkdir] Created dir: /mnt/1TB/var/tmp/portage/sci-biology/igv-2.3.40/work/IGV-2.3.40/testtmp
     [copy] Copying 141 files to /mnt/1TB/var/tmp/portage/sci-biology/igv-2.3.40/work/IGV-2.3.40/tmp
     [copy] Copied 109 empty directories to 52 empty directories under /mnt/1TB/var/tmp/portage/sci-biology/igv-2.3.40/work/IGV-2.3.40/tmp

prepare:
     [echo] Target File: /mnt/1TB/var/tmp/portage/sci-biology/igv-2.3.40/work/IGV-2.3.40/tmp/resources/about.properties
     [echo] Version user
     [echo] Build 0

rewrite-log:

compile:
    [javac] Compiling 866 source files to /mnt/1TB/var/tmp/portage/sci-biology/igv-2.3.40/work/IGV-2.3.40/tmp
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.

compileTests:
    [javac] Compiling 199 source files to /mnt/1TB/var/tmp/portage/sci-biology/igv-2.3.40/work/IGV-2.3.40/testtmp
    [javac] /mnt/1TB/var/tmp/portage/sci-biology/igv-2.3.40/work/IGV-2.3.40/test/src/util/FailedTestSelector.java:14: package org.apache.tools.ant does not exist
    [javac] import org.apache.tools.ant.BuildException;
    [javac]                            ^
    [javac] /mnt/1TB/var/tmp/portage/sci-biology/igv-2.3.40/work/IGV-2.3.40/test/src/util/FailedTestSelector.java:15: package org.apache.tools.ant.types does not exist
    [javac] import org.apache.tools.ant.types.Parameter;
    [javac]                                  ^
    [javac] /mnt/1TB/var/tmp/portage/sci-biology/igv-2.3.40/work/IGV-2.3.40/test/src/util/FailedTestSelector.java:40: package org.apache.tools.ant.types.selectors does not exist
    [javac] public class FailedTestSelector extends org.apache.tools.ant.types.selectors.BaseExtendSelector{
    [javac]                                                                             ^
    [javac] /mnt/1TB/var/tmp/portage/sci-biology/igv-2.3.40/work/IGV-2.3.40/test/src/util/FailedTestSelector.java:63: cannot find symbol
    [javac] symbol  : class Parameter
    [javac] location: class util.FailedTestSelector
    [javac]     public void setParameters(Parameter[] parameters){
    [javac]                               ^
    [javac] /mnt/1TB/var/tmp/portage/sci-biology/igv-2.3.40/work/IGV-2.3.40/test/src/util/FailedTestSelector.java:142: cannot find symbol
    [javac] symbol  : class BuildException
    [javac] location: class util.FailedTestSelector
    [javac]     public boolean isSelected(File directory, String filename, File file) throws BuildException {
    [javac]                                                                                  ^
    [javac] /mnt/1TB/var/tmp/portage/sci-biology/igv-2.3.40/work/IGV-2.3.40/test/src/util/FailedTestSelector.java:14: package org.apache.tools.ant does not exist
    [javac] import org.apache.tools.ant.BuildException;
    [javac]                            ^
    [javac] /mnt/1TB/var/tmp/portage/sci-biology/igv-2.3.40/work/IGV-2.3.40/test/src/util/FailedTestSelector.java:15: package org.apache.tools.ant.types does not exist
    [javac] import org.apache.tools.ant.types.Parameter;
    [javac]                                  ^
    [javac] /mnt/1TB/var/tmp/portage/sci-biology/igv-2.3.40/work/IGV-2.3.40/test/src/util/FailedTestSelector.java:40: package org.apache.tools.ant.types.selectors does not exist
    [javac] public class FailedTestSelector extends org.apache.tools.ant.types.selectors.BaseExtendSelector{
    [javac]                                                                             ^
    [javac] /mnt/1TB/var/tmp/portage/sci-biology/igv-2.3.40/work/IGV-2.3.40/test/src/util/FailedTestSelector.java:63: cannot find symbol
    [javac] symbol  : class Parameter
    [javac] location: class util.FailedTestSelector
    [javac]     public void setParameters(Parameter[] parameters){
    [javac]                               ^
    [javac] /mnt/1TB/var/tmp/portage/sci-biology/igv-2.3.40/work/IGV-2.3.40/test/src/util/FailedTestSelector.java:142: cannot find symbol
    [javac] symbol  : class BuildException
    [javac] location: class util.FailedTestSelector
    [javac]     public boolean isSelected(File directory, String filename, File file) throws BuildException {
    [javac]                                                                                  ^
    [javac] /mnt/1TB/var/tmp/portage/sci-biology/igv-2.3.40/work/IGV-2.3.40/test/src/util/FailedTestSelector.java:64: cannot find symbol
    [javac] symbol  : variable super
    [javac] location: class util.FailedTestSelector
    [javac]         super.setParameters(parameters);
    [javac]         ^
    [javac] /mnt/1TB/var/tmp/portage/sci-biology/igv-2.3.40/work/IGV-2.3.40/test/src/util/FailedTestSelector.java:65: cannot find symbol
    [javac] symbol  : class Parameter
    [javac] location: class util.FailedTestSelector
    [javac]         for(Parameter p: getParameters()){
    [javac]             ^
    [javac] /mnt/1TB/var/tmp/portage/sci-biology/igv-2.3.40/work/IGV-2.3.40/test/src/util/FailedTestSelector.java:65: cannot find symbol
    [javac] symbol  : method getParameters()
    [javac] location: class util.FailedTestSelector
    [javac]         for(Parameter p: getParameters()){
    [javac]                          ^
    [javac] /mnt/1TB/var/tmp/portage/sci-biology/igv-2.3.40/work/IGV-2.3.40/test/src/util/FailedTestSelector.java:62: method does not override or implement a method from a supertype
    [javac]     @Override
    [javac]     ^
    [javac] /mnt/1TB/var/tmp/portage/sci-biology/igv-2.3.40/work/IGV-2.3.40/test/src/util/FailedTestSelector.java:144: cannot find symbol
    [javac] symbol  : class BuildException
    [javac] location: class util.FailedTestSelector
    [javac]             throw new BuildException("Error processing result file", errorParsingReportFile);
    [javac]                       ^
    [javac] /mnt/1TB/var/tmp/portage/sci-biology/igv-2.3.40/work/IGV-2.3.40/test/src/util/FailedTestSelector.java:141: method does not override or implement a method from a supertype
    [javac]     @Override
    [javac]     ^
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 11 errors

BUILD FAILED
/mnt/1TB/var/tmp/portage/sci-biology/igv-2.3.40/work/IGV-2.3.40/build.xml:131: Compile failed; see the compiler error output for details.
</pre>

**Comment by jrobinso** [comment]
Hi, it looks like Ant is not installed correctly, or completely,  in 
particular you are missing the package org.apache.tools.ant.   Could you 
update your ant install to the latest and try again?

Jim

**Comment by mmokrejs** [comment]
I did update all ant-related packages but still, no luck. Notably, it does compile some files. Would you mind guessing where is the missing package hidden in Gentoo Linux?

<pre>
 * Using: oracle-jdk-bin-1.7
>>> Unpacking source...
>>> Unpacking v2.3.44.zip to /mnt/1TB/var/tmp/portage/sci-biology/igv-2.3.44/work
>>> Source unpacked in /mnt/1TB/var/tmp/portage/sci-biology/igv-2.3.44/work
>>> Preparing source in /mnt/1TB/var/tmp/portage/sci-biology/igv-2.3.44/work/IGV-2.3.44 ...
>>> Source prepared.
>>> Configuring source in /mnt/1TB/var/tmp/portage/sci-biology/igv-2.3.44/work/IGV-2.3.44 ...
Rewriting attributes
Rewriting ./launcher/build.xml
Rewriting ./docs/publishedApiDoclet/build.xml
Rewriting ./build.xml
>>> Source configured.
>>> Compiling source in /mnt/1TB/var/tmp/portage/sci-biology/igv-2.3.44/work/IGV-2.3.44 ...
 * Using following ANT_TASKS: ant-apache-bcel
Buildfile: /mnt/1TB/var/tmp/portage/sci-biology/igv-2.3.44/work/IGV-2.3.44/build.xml

clean:

init:
    [mkdir] Created dir: /mnt/1TB/var/tmp/portage/sci-biology/igv-2.3.44/work/IGV-2.3.44/tmp
    [mkdir] Created dir: /mnt/1TB/var/tmp/portage/sci-biology/igv-2.3.44/work/IGV-2.3.44/testtmp
     [copy] Copying 142 files to /mnt/1TB/var/tmp/portage/sci-biology/igv-2.3.44/work/IGV-2.3.44/tmp
     [copy] Copied 109 empty directories to 52 empty directories under /mnt/1TB/var/tmp/portage/sci-biology/igv-2.3.44/work/IGV-2.3.44/tmp

prepare:
     [echo] Target File: /mnt/1TB/var/tmp/portage/sci-biology/igv-2.3.44/work/IGV-2.3.44/tmp/resources/about.properties
     [echo] Version user
     [echo] Build 0

rewrite-log:

compile:
    [javac] Compiling 867 source files to /mnt/1TB/var/tmp/portage/sci-biology/igv-2.3.44/work/IGV-2.3.44/tmp
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.

compileTests:
    [javac] Compiling 197 source files to /mnt/1TB/var/tmp/portage/sci-biology/igv-2.3.44/work/IGV-2.3.44/testtmp
    [javac] /mnt/1TB/var/tmp/portage/sci-biology/igv-2.3.44/work/IGV-2.3.44/test/src/util/FailedTestSelector.java:14: error: package org.apache.tools.ant does not exist
    [javac] import org.apache.tools.ant.BuildException;
    [javac]                            ^
</pre>

Other ant-based packages can be compiled without problems.

**Comment by jrobinso** [comment]
Hi,  that package is part of "ant.jar" and should be found.  We do have 
a copy in test/lib/ant.jar,  you might try including that jar (and all 
the jars in test/lib) to see if it helps.   If it does please reply here 
to let us know.

Jim
