### ISSUE TITLE
Can not load .genome file created on different machine

### ISSUE THREAD

**Issue by alexjironkin** [broadinstitute/IGV#123]
Hello,

I am not certain whether this is by design or accident, but if I create a genome file from IGV and distribute it to someone else, they can't load it because FASTA index file is missing from the archive. Or rather, it is trying to find it in the same directory as the .genome file, load it, but fails.

Can the fai file be bundled together with other files in the genome archive, so it is self contained and doesn't require any additional files to be transferred?

**Comment by jrobinso** [comment]
Hi, that is how it currently works, it wasn't in the original design to 
distribute fastas in that way, and it would be complex to do so.   The 
fasta index must remain with the fasta file, and both need to be 
reachable (normally by URL).  If you intend to distribute the .genome 
file you should enter the URL to the fasta in the field for that 
purpose, the fai file will be found automatically as <fasta url>.fai.

If you want to distribute your fasta files and not host them you can do 
so,  they just need to have the same relative path with respect to the 
.genome file.    So you could, for example, keep them all the the same 
directory then zip .genome, fasta, and fai file to have a single file to 
distribute.   The end user would need to unzip it.

Jim

**Comment by alexjironkin** [comment]
Hi,

As you mentioned, we are not planning on hosting the FASTA files, so there is no URL to provide. Our current fix was to provide the fai file and ask to keep them together, but you can imagine it's not ideal.

FASTA file can already be bundled into the genome file and specified in sequenceLocation property, can we not add the support for index file to be picked up from the same archive? Otherwise, it seems like a disparity in required files, when no URLs are available. Perhaps this is something that has already been scheduled for in the future, or decided not to be done?


Alex

**Comment by jrobinso** [comment]
Actually bundling the fasta file should not work,  it will not be in the 
.genome file.   If you unzip the .genome file you will see that (its 
just a zip file with a .genome extension).    The best solution for you 
is to have fasta, fai, and .genome file in the same directory and zip 
them all.   This seems simple to do and easy to distribute.

The reason the fasta file cannot be in the .genome file is the 
compression process would invalidate the index.   The assumption is that 
fasta files are generally too large to use without the index. Of course 
for some organisms this is not the case,  but currently we require an index.

Jim

**Comment by alexjironkin** [comment]
Yeah we know it's just a zip file, I manually added the fasta file and modified the property.txt to include it and IGV only complained about missing index file. We deal with viral/microbial genomes so they are small and FASTA files are manageable.

I appreciate your position, and it would be great if IGV could check index file in .genome if it exists in the future releases.

**Comment by jrobinso** [comment]
Hi,

I'm not sure I'm communicating properly,  but FASTA files will not work 
when zipped when using an index,  the byte positions are changed by the 
compression and the index is no longer valid.    So manually adding the 
fasta file will not work even if the .fai file were added.    What could 
be done for a future release is allow loading a fasta complete without 
an index.   I agree that would be a good addition.

Is that clear?

Jim

**Comment by jrobinso** [comment]
Are your genomes available as genbank (.gbk) files?   If so you can just 
load them directly without creating a .genome file,  which loads 
sequence and annotations.

**Comment by alexjironkin** [comment]
I assumed IGV extracts content internally and works from that. 

Some are available in genebank, some are not. We deal with very diverse range of species. But I didn't know I could just use genbank file directly. Can I load it with Genomes > Load Genome from file?

**Comment by jrobinso** [comment]
Yes,  Load Genomes from file...   works with genbank files. Extension 
should be .gbk or .gb.

Jim

**Comment by jrobinso** [comment]
I'm going to close this issue and open an enhancement request to embed the fasta sequence in the .genome file.
