### ISSUE TITLE
Display of long deletions from VCF (and probably other formats)

### ISSUE THREAD

**Issue by jsilter** [broadinstitute/IGV#13]
Hi,

Long deletions in VCF files are handled poorly being represented as a single unwrapped string.

It would be preferable if this was represented as something like:

ACGTACT...ACGTACGT (8,000bp)

When this occurs in a SAM record the deleted seq is wrapped (but that still runs into problems).

IGV 2.1.21, MacOS 10.6.8

Regards,

Keiran Raine
Principal Bioinformatician
Cancer Genome Project
Wellcome Trust Sanger institute

**Comment by jrobinso** [comment]
Closing due to age, and many changes to VCF in the interim.  If its still and issue please open a new ticket with an example file.
