### ISSUE TITLE
Batch script problems

### ISSUE THREAD

**Issue by hepcat72** [broadinstitute/IGV#44]
So I discovered this problem after finding a work-around for the coverage track height issue I submitted yesterday.  Running the same batch script in version 2.0.3 and 2.3.3 runs really fast in 2.0.3, but in 2.3.3, it takes a really long time.  I watched it for minutes redraw the same data 6 times before performing the snap shot.  I would watch the window clear out to be almost completely blank (other than the pane borders) and then watch the data get redrawn slowly from bottom to top, left to right - then clear out again and redraw the same position, same data, same exact overall image 5 more times, bottom to top, left to right.  In version 2.0.3, all the data appears instantaneously.  Once.  Then it takes the snapshot.  Here's the batch script:

snapshotDirectory /panfs/panfs.ccr.buffalo.edu/projects/ccrstaff/rwleach/PROJECT/CRPC/MACS/snapshots
goto chr10:73150690-73162690
setDataRange 0,40
snapshot CDH23.chr10.73151690-73161690.png
goto chr10:73549527-73561527
snapshot CDH23.tss2.chr10.73550527-73560527.png
goto chr10:73565639-73577639
snapshot CDH23.tss3.chr10.73566639-73576639.png
goto chr1:12117433-12129433
snapshot TNFRSF8.chr1.12118433-12128433.png

In the time it takes 2.3.3 to do this test portion of data, I can screen cap about 100 positions in version 2.0.3.  Why does it draw each position's data 6 times, slowly?  Is there a way I can alleviate this myself?

Thanks,
Rob

PS - Separate issue: when a slightly different script is launched via the command line, the whole thing hangs and seemingly gets stuck.  Here' the head of the other script:

new
load /projects/ccrstaff/rwleach/PROJECT/CRPC/MACS/LNCaPDHT-LNCaP-datarange40.xml
snapshotDirectory /panfs/panfs.ccr.buffalo.edu/projects/ccrstaff/rwleach/PROJECT/CRPC/MACS/LNCaPDHT-LNCaP-datarange40.xml.snapshots/hg19_SimpleTxStartCoords20130226-strand.txt.pad20k.forigv10k.uniq.igv-dir
goto chr10:73150690-73162690
snapshot CDH23.chr10.73151690-73161690.png
goto chr10:73549527-73561527
snapshot CDH23.tss2.chr10.73550527-73560527.png
goto chr10:73565639-73577639
snapshot CDH23.tss3.chr10.73566639-73576639.png
goto chr1:12117433-12129433

**Comment by jrobinso** [comment]
Closing this issue.  I do have not additional suggestions for running over X11, and unfortunately its not something we can support with the resources we have.
