### ISSUE TITLE
ENHANCEMENT REQUEST: "Feature Flanking Region" can now be expressed as a multiplier of feature size

### ISSUE THREAD

**Issue by malcook** [broadinstitute/IGV#55]
Suggested replacement for text http://www.broadinstitute.org/software/igv/Preferences

Change this to define how large a flanking region IGV will add before and after a feature locus when you zoom to a feature, or when you view gene/loci lists in multiple panel.  Integers values are taken as number of  base pairs.  Real number values are taken as a scaling multiplier (for example, 1.5 will zoom out to 150% of the feature's size, resulting in 25% of the feature's size on either side).

**Comment by jrobinso** [comment]
Implemented long ago, just now closing git issue.   We've switched at long last from our internal "Jira" system to git issues, cleaning up.
