### ISSUE TITLE
Performance Regression over X11

### ISSUE THREAD

**Issue by jimhester** [broadinstitute/IGV#60]
There is a major performance regression in IGV that has existed since version 2.2 was released, which makes newer versions unbearably slow when using X11.  I assume it is still the same issue as https://groups.google.com/forum/#!topic/igv-help/jR1Z8ITFcXM

I have tried to disable anti-aliasing to fix the problem as mentioned in that email chain, but the preference does not seem to be checked everywhere, in particular the read display themselves seem to still be antialiased.  Performance is as you would expect very bad due to this problem.

2.1.24 performance is very snappy over X11, so I will continue to use that, but it would be nice to fix this performance regression so that those of us using IGV over the network can use the new features!

**Comment by jrobinso** [comment]
Closing X11 issues,  given the very limited resources available for IGV development (i.e. me) I just can't pursue this.   I would welcome pull requests on the issue.   Perhaps Java 1.8 will have made some improvements in this regard.
