### ISSUE TITLE
Highlight chimeric alignments

### ISSUE THREAD

**Issue by sjackman** [broadinstitute/IGV#64]
I've mapped assembled contigs to a reference genome using BWA-MEM. One of these contigs indicates structural rearrangement, and so there are two alignments, and one has the "supplementary alignment" flag (2048 or 0x800) set. It'd be great if IGV could highlight both of these alignments.

This could be done by adding a feature to highlight alignments that have the chimeric flag set. Hovering over that alignment would reveal its name. Highlighting both alignments could be accomplished using "Select by name...".

**Comment by jrobinso** [comment]
Some support for supplementary alignments was added late last year, specifically

* Supplementary alignments are outlined in blue.
* Supplementary alignments can be filtered out of the view (new alignment preferences option).
* Alignments can be "grouped" by the supplementary tag,  thus separating supplementary and non-supplementary alignments.

**Comment by sjackman** [comment]
Thanks, Jim.
