### ISSUE TITLE
Unknown file type: GenBank gbk

### ISSUE THREAD

**Issue by sjackman** [broadinstitute/IGV#74]
I select *File -> Open* and select a GenBank .gbk file. I get the following error message:

> Unknown file type: scaffolds.gbk Check file extension

I believe GenBank .gbk files are supported by IGV since 2.2.x:
http://www.broadinstitute.org/igv/IGV2.2.x

> New file formats. IGV now supports GenBank (.gbk) files

I am using IGV version 2.3.23 (26).

Cheers,
Shaun

**Comment by jrobinso** [comment]
The genbank file referenced loads for me in 2.3.46.   Upon reflection allowing loading genbanks for the annotations would likely cause confusion,  and I can't think of a strong case to justify the effort required to do it.
