### ISSUE TITLE
error loading gtf file

### ISSUE THREAD

**Issue by bwlang** [broadinstitute/IGV#79]
the text of the error is :
Error Loading mouse_mm10_gencode_M2_GTF.chrM.sorted.gtf: class "org.broad.igv.track.TribbleFeatureSource$NonIndexedFeatureSource$CoverageDataSource" does not match trust level of other classes in the same package.

Let me know if you need more information to find the source of this this problem.

**Comment by jrobinso** [comment]
Closing, can't reproduce.
