### ISSUE TITLE
IGV + proxy + custom DAS server running on localhost

### ISSUE THREAD

**Issue by lindenb** [broadinstitute/IGV#86]
( cross posted on https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/igv-help/bj0UtZA2fxs/bERdGfs4onQJ)

Hi IGV team,

I'm trying to display the content of a custom **DAS** server running on **localhost:8080**.

I'm working behind a proxy.

In preferences>proxy, I set the  HTTP proxy host and port

I also edited igv.sh and added :
```
             (...) \
             -Dhttp.nonProxyHosts=localhost \
```

But I still get a "Can't connect to SOCKS proxy:Connection refused"

(I also tried various combinations:  settings http.proxyHost and http.proxyPort in igv.sh and/or disabling preferences>proxy, set the proxy by ${JAVA_HOME}/bin/ControlPanel .... )

how can I fix this proxy problem ?

Thank you

Pierre

**Comment by jrobinso** [comment]
Pierre, is this still a problem?  I use a local proxy frequently, CharlesProxy to be exact, and this is the error I get if I have forgotten to start it up.

**Comment by lindenb** [comment]
I had forgotten this + I give up . I can have a look next week.

**Comment by lindenb** [comment]
No I get a 503. 

```
ERROR [2015-03-23 11:34:10,157]  [HttpUtils.java:751] [pool-1-thread-6]  Code: 503. Service Unavailable
ERROR [2015-03-23 11:34:10,157]  [DASFeatureSource.java:207] [pool-1-thread-6]  org.broad.igv.exceptions.HttpResponseException: HTTP access error (status code 503)
INFO [2015-03-23 11:34:10,160]  [MessageUtils.java:60] [pool-1-thread-6]  <html>The DAS Server: http://localhost/divandb/ has returned an error or invalid data.<br>HTTP access error (status code 503)
```

while I see the DAS XML in my browser. My custom DAS server doesn't log any request.

last time, I played with specifiting http.proxyHost, etc... within igv.sh but I don't really have time to do this again. (as far as I can see IGV ignores the DAS entry on error and therefore must be restarted each time it gets a 503 ).

**Comment by jrobinso** [comment]
Do you know what is returning the 503?  The 503 and lack of a log entry 
would seem to imply the request is not reaching your DAS server.  A 
network traffic trace would be helpful   You sometimes need to specify a 
proxy in IGV preferences (view > Advanced,  for reasons I've never been 
able to track down the environment variable settings are not always 
picked up.

I can't really reproduce this in my local environment.

Jim

**Comment by jrobinso** [comment]
Can't reproduce
