### ISSUE TITLE
Graphical Fragment Assembly format

### ISSUE THREAD

**Issue by sjackman** [broadinstitute/IGV#97]
Heng Li has proposed a common assembly graph file format called GFA (Grapical Fragment Assembly). The proposal is here:

+ [First update on GFA](http://lh3.github.io/2014/07/23/first-update-on-gfa/)
+ [A proposal of the Graphical Fragment Assembly format](http://lh3.github.io/2014/07/19/a-proposal-of-the-grapical-fragment-assembly-format/)

When browsing BAM files of reads aligned to contigs, it’s helpful to know which contig(s) precede and follow the contig that you’re currently looking at, and also see whether there’s any sequence overlap with that contig. Would you consider adding support for GFA to IGV? It’s similar in nature to SAM. I’d love to have the feedback from the perspective of a developer implementing a browser, if you’d like to add your comments to Heng’s blog post. ABySS will support the GFA in its next release.

Cheers,
Shaun

**Comment by jrobinso** [comment]
I think this is a bit out of scope, or at least out of scope given the project resources (I am the "resources").  Also, there has been no update on the proposal since last September.
