### ISSUE TITLE
Colour by Pair Orientation Only on Plus Strand

### ISSUE THREAD

**Issue by nathanhaigh** [broadinstitute/IGV#99]
It seems IGV is only colouring reads based on pair orientation for reads on the plus strand. See below image for reads grouped by strand and coloured by pair orientation.

![igv](https://cloud.githubusercontent.com/assets/2037575/4246403/369b5dfc-3a4a-11e4-8f3a-329b1535b173.png)

**Comment by jrobinso** [comment]
Closing because I can't reproduce the problem.
